### ISSUE TITLE
Italics have unusual line alignment?

### ISSUE THREAD

**Issue by emmiegit** [Nu-SCPTheme/Black-Highlighter#224]
**Describe the issue:**  
Italics appear strangely in-line, rather than being like other text they appear to be slightly subscripted.

**Screenshot showcasing the issue:**  
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8848022/53e97774-9d80-4691-a9c7-cd8533f1eb4a)

**Link to the page(s) having this issue:**  
https://scp-wiki.wikidot.com/scp-6140/offset/1 Addendum 1 table

**Device information:** (fill in as appropriate)  
 - Device: Desktop
 - OS: Arch Linux, kernel 6.5.9, Xorg
 - Browser: Firefox Developer Edition
 - Version: Firefox 120.0b6 (64-bit)

**Comment by SYwaves** [comment]
It's due to this rule:
`
#page-content div.b-tables table.wiki-content-table, #page-content div.b-tables table.wiki-content-table *, #page-content table.wiki-content-table, #page-content table.wiki-content-table * {
    --min-font-size: 0.8125rem;
    vertical-align: middle;
}
`

Where 'vertical align' causes the odd alignment. Reducing the scope of the selector should be done here.

**Comment by Woedenaz** [comment]
It's not just affecting the italics, it's doing it to any inline element. Very strange.

changing it to this potentially fixes the issue but I need to make sure it doesn't break anything else:
```css
}
#page-content div.b-tables table.wiki-content-table,
#page-content div.b-tables table.wiki-content-table td,
#page-content table.wiki-content-table,
#page-content table.wiki-content-table td {
  --min-font-size:0.8125rem;
  vertical-align:middle;
}
```
